### ISSUE TITLE
Documentation is grossly misleading

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-filter-uuid#6]
The documentation of this plugin states that it's

> useful to be able to control the _id messages are indexed into Elasticsearch with, so that you can insert duplicate messages (i.e. the same message multiple times without creating duplicates)

which is completely false. UUIDs are unique every time they're generated; that's their raison d'être. The UUID generation does not in any way take the event contents into account.

**Comment by suyograo** [comment]
Fixed in #7
